### ISSUE TITLE
为何运行一直报错

### ISSUE THREAD

**Issue by jzhangdev** [LancerComet/Aniber#3]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'selenium-start' ]
2 info using npm@3.7.2
3 info using node@v4.3.0
4 verbose run-script [ 'preselenium-start', 'selenium-start', 'postselenium-start' ]
5 info lifecycle aniber@0.1.0~preselenium-start: aniber@0.1.0
6 silly lifecycle aniber@0.1.0~preselenium-start: no script for preselenium-start, continuing
7 info lifecycle aniber@0.1.0~selenium-start: aniber@0.1.0
8 verbose lifecycle aniber@0.1.0~selenium-start: unsafe-perm in lifecycle true
9 verbose lifecycle aniber@0.1.0~selenium-start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\dev\Aniber\node_modules.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\JZhang\AppData\Local.meteor\;C:\python27;C:\python27\Scripts;C:\Users\JZhang\AppData\Roaming\npm;D:\Program Files.babun;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\JZhang\AppData\Local\atom\bin;C:\php5;C:\Program Files\Docker Toolbox
10 verbose lifecycle aniber@0.1.0~selenium-start: CWD: F:\dev\Aniber
11 silly lifecycle aniber@0.1.0~selenium-start: Args: [ '/d /s /c', 'node ./build/selenium-start.js' ]
12 silly lifecycle aniber@0.1.0~selenium-start: Returned: code: 1  signal: null
13 info lifecycle aniber@0.1.0~selenium-start: Failed to exec selenium-start script
14 verbose stack Error: aniber@0.1.0 selenium-start: `node ./build/selenium-start.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid aniber@0.1.0
16 verbose cwd F:\dev\Aniber
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "selenium-start"
19 error node v4.3.0
20 error npm  v3.7.2
21 error code ELIFECYCLE
22 error aniber@0.1.0 selenium-start: `node ./build/selenium-start.js`
22 error Exit status 1
23 error Failed at the aniber@0.1.0 selenium-start script 'node ./build/selenium-start.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aniber package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./build/selenium-start.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aniber
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aniber
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by LancerComet** [comment]
@jzhangdev 您之前运行过 `npm run selenium-setup` 命令来安装 Selenium 么？这个 npm 的日志看不出 Selenium 运行的错误，只能判断其报错内容和没有安装 Selenium 时一样。

在运行 `npm run selenium-start` 之后，如果运行失败，终端内会出现一条内容 “Error: Selenium 启动失败: [失败原因]”，您可以检查这条报错并反馈回来 :)
