### ISSUE TITLE
运行start 报错

### ISSUE THREAD

**Issue by yelingfeng** [LancerComet/Aniber#4]
![image](https://cloud.githubusercontent.com/assets/1932350/17239581/bdbbd41e-5597-11e6-9549-9d18c4406a81.png)
![image](https://cloud.githubusercontent.com/assets/1932350/17239624/24421e00-5598-11e6-846c-d0b228b77d02.png)

**Comment by LancerComet** [comment]
@yelingfeng 看起来是 Selenium 没有启动成功，如果使用 `npm run selenium-start` 单独启动 Selenium 会有什么报错么？另外确保您已经装了 Java 运行环境和使用 `npm run selenium-setup` 安装了 Selenium.

**Comment by yelingfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1932350/17280530/4c8be700-57c4-11e6-9597-c7b631144a8b.png)
![image](https://cloud.githubusercontent.com/assets/1932350/17280531/5184cbb4-57c4-11e6-9be8-fc4d5b6e179f.png)
单独启动报这个
![image](https://cloud.githubusercontent.com/assets/1932350/17280537/76572e1e-57c4-11e6-9d17-78df257c4368.png)

**Comment by LancerComet** [comment]
@yelingfeng 您是看着 segmentfault 的文章自己搭建的吧，我回头去看了一下文章，发现有一个地方由于在下的个人疏漏写错了:( ，十分抱歉

您可以看下方的方法修复，也可以从当前 Repo 中 Clone 一份下来，Repo 中的代码没有问题。

修复：
打开 `./build/selenium-start.js` 文件，然后看这一段：

```
selenium.start({
       drivers: seleniumConfig.driver
   }, function (err) {
       if (err) throw new Error(`Selenium 启动失败: ${err}`)
       console.log(`Selenium 已手工启动，进程 PID: ${child.pid}`)
       console.log('当不再需要运行 Selenium 时可关闭此 PID 进程.')
   })
```

您需要在回调函数中再加入一个参数 `child`，所以看起来应该是

```
selenium.start({
       drivers: seleniumConfig.driver
   }, function (err, child) {
       if (err) throw new Error(`Selenium 启动失败: ${err}`)
       console.log(`Selenium 已手工启动，进程 PID: ${child.pid}`)
       console.log('当不再需要运行 Selenium 时可关闭此 PID 进程.')
   })
```

Segmentfault 上的问题已经同样修复了 :+1:

**Comment by yelingfeng** [comment]
ok了已经 倒不是这个child没传过来的问题 是nightwatch 不会自动启动selenimserver吗？

**Comment by LancerComet** [comment]
正常情况下会自动启动，如果没有自动启动可能是配置的时候哪里漏掉了，您可以再检查一下
