### ISSUE TITLE
安装Selenium 安装错误:

### ISSUE THREAD

**Issue by guoxiangwen** [LancerComet/Aniber#5]
rror: Selenium 安装错误: Error: Could not download https://selenium-release.storage.googleapis.
com/2.53/selenium-server-standalone-2.53.1.jar: Error: connect ETIMEDOUT 74.125.23.128:443
有国内的镜像吗？

**Comment by LancerComet** [comment]
木有，我帮您上传到百度网盘了：
http://pan.baidu.com/s/1migBgso

不过还是翻墙后安装比较吼

**Comment by guoxiangwen** [comment]
多谢，淘宝有mirror。不过我没用selenium-server-standalone。仿照vue-cli搭建起来了
