### ISSUE TITLE
您好，不知道为什么seleniem出问题了

### ISSUE THREAD

**Issue by 1o1w1** [LancerComet/Aniber#8]
更新了下版本发现npm run chrome能启动了，但是npm start能跑的两个测试用例npm run chrome都报错。不同浏览器还要写不同的测试用例吗  0 0

**Comment by LancerComet** [comment]
如果方便还请贴一下报错日志，`npm start` 默认使用的是 `PhantomJS`，Chrome 执行失败可能是 `Chrome Driver` 没有正确安装 😎

**Comment by 1o1w1** [comment]
搞定啦，试着把chrome版本降低下就没问题啦

**Comment by LancerComet** [comment]
唔，我是 Chrome 61 运行是正常的，如果可以的话还是希望能提供一下报错日志和浏览器版本，暂时先 Close 了
