### ISSUE TITLE
nightwatch怎么点击select选中对应的option呀

### ISSUE THREAD

**Issue by 1o1w1** [LancerComet/Aniber#9]
把select点开之后，使用.click无法点击option进行点击。也尝试使用了.moveToElement先定位select然后将鼠标移动到下面点击option，发现还是点不到。我把api翻了一遍都没看到关于select操作的接口。很是迷惑呀

**Comment by LancerComet** [comment]
您试试以下方式：

```html
<!-- 测试目标 -->
<select name="test-select">
  <option value="comet">Comet</option>
  <option value="lancer">Lancer</option>
  <option value="aniber">Aniber</option>
</select>
```

```javascript
client.click('select[test-select]', () => {
  client.click('option[value="lancer"]')
})
```

在对一个目标进行点击后，如需对目标进行下一步处理，可以放置在 callback 中进行.

[Nightwatch API - Click Command](http://nightwatchjs.org/api#click)
